# Erigon by default is "all in one binary" solution, but it's possible start TxPool as separated processes.
# Same true about: JSON RPC layer (RPCDaemon), p2p layer (Sentry), history download layer (Downloader), consensus.
# Don't start services as separated processes unless you have clear reason for it: resource limiting, scale, replace by your own implementation, security.
# This file is an example: how to start Erigon's services as separated processes.

# Default: --datadir=/home/erigon/.local/share/erigon
# Default UID: 3473
# Default GID: 3473
# Ports: `9090` execution engine (private api), `9091` sentry, `9092` consensus engine, `9093` snapshot downloader, `9094` TxPool
# Ports: `8545` json rpc, `8551` consensus json rpc, `30303` eth p2p protocol, `42069` bittorrent protocol,

# Connections: erigon -> (sentries, downloader), rpcdaemon -> (erigon, txpool), txpool -> erigon

version: '2.2'

# Basic erigon's service
# ${TAG:-latest}
x-erigon-service: &default-erigon-service
  image: thorax/erigon:v2.28.1
  pid: service:erigon # Use erigon's PID namespace. It's required to open Erigon's DB from another process (RPCDaemon local-mode)
  volumes_from: [ erigon ]
  restart: unless-stopped
  mem_swappiness: 0
  user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}

services:
  erigon:
    image: thorax/erigon:v2.28.1
    build:
      args:
        UID: ${DOCKER_UID:-1000}
        GID: ${DOCKER_GID:-1000}
      context: .
    command: |
      erigon ${ERIGON_FLAGS-}
      --chain=mainnet
      --private.api.addr=0.0.0.0:9090 
      --sentry.api.addr=sentry:9091 
      --downloader.api.addr=downloader:9093 
      --txpool.disable 
      --authrpc.addr=0.0.0.0 
      --authrpc.vhosts=* 
      --http.vhosts=* 
      --http.corsdomain=*
      --metrics 
      --metrics.addr=0.0.0.0 
      --metrics.port=6060 
      --pprof 
      --pprof.addr=0.0.0.0 
      --pprof.port=6061
      --authrpc.jwtsecret=/home/erigon/.local/share/erigon/jwt.hex
      --datadir=/home/erigon/.local/share/erigon
    ports: [ "8551:8551" ]
    volumes:
      # It's ok to mount sub-dirs of "datadir" to different drives
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
    restart: unless-stopped
    mem_swappiness: 0

  sentry:
    <<: *default-erigon-service
    command: sentry ${SENTRY_FLAGS-} --sentry.api.addr=0.0.0.0:9091 --datadir=/home/erigon/.local/share/erigon
    ports: [ "30303:30303/tcp", "30303:30303/udp" ]

  downloader:
    <<: *default-erigon-service
    command: downloader ${DOWNLOADER_FLAGS-} --downloader.api.addr=0.0.0.0:9093 --datadir=/home/erigon/.local/share/erigon
    ports: [ "42069:42069/tcp", "42069:42069/udp" , "9093:9093/tcp", "9093:9093/udp"]

  txpool:
    <<: *default-erigon-service
    command: txpool ${TXPOOL_FLAGS-} --private.api.addr=erigon:9090 --txpool.api.addr=0.0.0.0:9094 --sentry.api.addr=sentry:9091 --datadir=/home/erigon/.local/share/erigon

  rpcdaemon:
    <<: *default-erigon-service
    command: |
      rpcdaemon ${RPCDAEMON_FLAGS-} --http.addr=0.0.0.0 --http.vhosts=* --http.corsdomain=* --ws --http.api=eth,erigon,web3,net,debug,trace,txpool
      --private.api.addr=erigon:9090 --txpool.api.addr=txpool:9094 --datadir=/home/erigon/.local/share/erigon --rpc.accessList=/home/erigon/.local/share/erigon/rules.json
    ports: [ "8545:8545" ]


  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:v3.1.1
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
    command: --datadir=/prysm-data --rpc-host=0.0.0.0 --monitoring-host=0.0.0.0 --execution-endpoint=http://erigon:8551 --jwt-secret=/home/erigon/.local/share/erigon/jwt.hex --accept-terms-of-use --grpc-gateway-host=0.0.0.0 --grpc-gateway-corsdomain='*' --checkpoint-sync-url=https://beaconstate.info --genesis-beacon-api-url=https://beaconstate.info
    ports:
      - "3500:3500"
      - "13000:13000"
      - "12000:12000/udp"
    volumes:
      - ${XDG_DATA_HOME:-~/.local/share}/erigon:/home/erigon/.local/share/erigon
      - ${XDG_DATA_HOME:-~/.local/share}/prysm-data:/prysm-data
    depends_on:
      - "erigon"
    restart: unless-stopped
    mem_swappiness: 0
    
#  ethereum-metrics-exporter:
#    image: samcm/ethereum-metrics-exporter:latest
#    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
#    command: --consensus-url=http://prysm:3500 --execution-url=http://rpcdaemon:8545
#    ports: [ "8001:9090" ]
#    restart: unless-stopped
    
  prometheus:
    image: prom/prometheus:v2.39.1
    user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000} # Uses erigon user from Dockerfile
    command: --log.level=warn --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=150d --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles
    ports: [ "9090:9090" ]
    volumes:
      - ${ERIGON_PROMETHEUS_CONFIG:-./cmd/prometheus/prometheus.yml}:/etc/prometheus/prometheus.yml
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-prometheus:/prometheus
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.2.1
    user: "472:0" # required for grafana version >= 7.3
    ports: [ "3000:3000" ]
    volumes:
      - ${ERIGON_GRAFANA_CONFIG:-./cmd/prometheus/grafana.ini}:/etc/grafana/grafana.ini
      - ./cmd/prometheus/datasources:/etc/grafana/provisioning/datasources
      - ./cmd/prometheus/dashboards:/etc/grafana/provisioning/dashboards
      - ${XDG_DATA_HOME:-~/.local/share}/erigon-grafana:/var/lib/grafana
    restart: unless-stopped

