{
 "title": "Ethereum Metrics Exporter (Single)",
 "description": "A companion dashboard for https://github.com/samcm/ethereum-metrics-exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values({ethereum_role!=\"\"}, instance)"
    }
   },
   { "name": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Execution Client",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_admin_node_info{instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Consensus Config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_spec_config_name{instance=~\"$instance\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Consensus Preset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_spec_preset_base{instance=~\"$instance\"}",
     "legendFormat": "{{ preset }}"
    }
   ]
  },
  {
   "title": "Consensus Network ID",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_network_id{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Consensus Fork",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_fork_current{instance=~\"$instance\"}",
     "legendFormat": "{{ fork }}"
    }
   ]
  },
  {
   "title": "Consensus Client",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_node_version{instance=~\"$instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "🐼 The Merge",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_exe_admin_total_difficulty_trillions{instance=~\"$instance\"} > 5\n)",
     "legendFormat": "Current Total Difficulty"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_spec_terminal_total_difficulty_trillions{instance=~\"$instance\"} > 5\n)",
     "legendFormat": "Terminal Total Difficulty"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_spec_terminal_total_difficulty{instance=~\"$instance\"} < 5 * 1e12\n)",
     "legendFormat": "Terminal Total Difficulty"
    },
    {
     "expr": "sum by (instance)(\n    eth_exe_admin_total_difficulty{instance=~\"$instance\"} < 5 * 1e12\n)",
     "legendFormat": "Current Total Difficulty"
    }
   ]
  },
  {
   "title": "Execution Chain ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_chain_id{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Execution Network ID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_network_id{instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Consensus Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_con_sync_is_syncing{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eth_con_sync_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slots",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 11 },
   "targets": [
    {
     "expr": "sum by (identifier)(\n    eth_con_slot_number{instance=~\"$instance\", identifier!=\"genesis\"}\n)",
     "legendFormat": "{{ identifier }}"
    }
   ]
  },
  {
   "title": "Epochs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 11 },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n)\n/\nsum by (instance)(\n    eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n)",
     "legendFormat": "Head"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"finalized\"}\n)\n/\nsum by (instance)(\n    eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n)",
     "legendFormat": "Finalized"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"justified\"}\n)\n/\nsum by (instance)(\n    eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n)",
     "legendFormat": "Justified"
    }
   ]
  },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "eth_con_sync_distance{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(eth_con_sync_percentage{instance=~\"$instance\"})[1m]",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Slot distances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Slots" } },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n)\n-\nsum by (instance) (\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"finalized\"}\n) ",
     "legendFormat": "Head -> Finalized"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n)\n-\nsum by (instance) (\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"justified\"}\n) != 0",
     "legendFormat": "Head -> Justified"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"justified\"}\n)\n-\nsum by (instance) (\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"finalized\"}\n) != 0",
     "legendFormat": "Justified -> Finalized"
    }
   ]
  },
  {
   "title": "Epoch distances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Epochs" } },
   "targets": [
    {
     "expr": "(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)\n-\n(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"justified\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)",
     "legendFormat": "Head -> Justified"
    },
    {
     "expr": "(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)\n-\n(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"finalized\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)",
     "legendFormat": "Head -> Finalied"
    },
    {
     "expr": "(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"justified\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)\n-\n(\n    sum by (instance)(\n        eth_con_slot_number{instance=~\"$instance\", identifier=\"finalized\"}\n    )\n    /\n    sum by (instance)(\n        eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n    )\n)",
     "legendFormat": "Justified -> Finalized"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance)(increase(eth_con_reorg_count{instance=~\"$instance\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Reorg Depth",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 23 },
   "targets": [
    {
     "expr": "sum by (instance)(increase(eth_con_reorg_depth{instance=~\"$instance\"}))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Fork Epochs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_con_fork_epoch{instance=~\"$instance\"}",
     "legendFormat": "{{ fork }}"
    },
    {
     "expr": "sum by (instance)(\n    eth_con_slot_number{instance=~\"$instance\", identifier=\"head\"}\n) \n/\nsum by (instance) (\n    eth_con_spec_slots_per_epoch{instance=~\"$instance\"}\n)",
     "legendFormat": "Current head epoch"
    }
   ]
  },
  { "title": "Execution Layer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Sync Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_exe_sync_is_syncing{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Sync Percent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eth_exe_sync_percentage{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_most_recent_block_number{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "eth_exe_admin_peers{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync Distance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "blocks" } },
   "targets": [
    {
     "expr": "eth_exe_sync_highest_block{instance=~\"$instance\"} - eth_exe_sync_current_block{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Sync rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(eth_exe_sync_percentage{instance=~\"$instance\"})[1m]",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Gas Price",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Gwei" } },
   "targets": [
    {
     "expr": "eth_exe_gas_price_gwei{instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Total Difficulty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 36 },
   "targets": [
    {
     "expr": "sum by (instance)(\n    eth_exe_admin_total_difficulty_trillions{instance=~\"$instance\"}\n)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Consensus Spec",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus Spec",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "sum by (spec)(\n    label_replace(\n        {__name__=~\"eth_con_spec.*\"},\n        \"spec\",\n        \"$1\",\n        \"__name__\",\n        \"eth_con_spec_(.*)\"\n    )\n)",
       "legendFormat": "{{ spec }}"
      }
     ]
    }
   ]
  }
 ]
}